# Generated by Django 4.2.11 on 2026-09-10 23:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(default='Sysvar Hub', max_length=100)),
                ('empresa_id', models.PositiveBigIntegerField()),
                ('loja_id', models.PositiveBigIntegerField()),
                ('retaguarda_url', models.URLField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_sincronizacao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Hub',
                'verbose_name_plural': 'Configurações do Hub',
            },
        ),
    ]
