# Generated by Django 4.2.11 on 2026-09-10 23:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('caixa_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=150)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_conexao_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminais', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminais',
                'ordering': ('codigo', 'nome'),
            },
        ),
    ]
