# Generated by Django 4.2.11 on 2026-09-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='ativado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='empresa_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='loja_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='retaguarda_hub_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='retaguarda_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='ultimo_heartbeat_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubconfig',
            name='empresa_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubconfig',
            name='loja_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
