# Generated by Django 4.2.11 on 2026-09-11 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_hubconfig_ativado_em_hubconfig_empresa_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hubconfig",
            name="bootstrap_versao",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hubconfig",
            name="loja_apelido",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="hubconfig",
            name="loja_cnpj",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="hubconfig",
            name="loja_estado",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
        migrations.CreateModel(
            name="CaixaHub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retaguarda_id", models.PositiveBigIntegerField()),
                ("codigo", models.CharField(max_length=30)),
                (
                    "descricao",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("sincronizado_em", models.DateTimeField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caixas",
                        to="core.hubconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caixa do Hub",
                "verbose_name_plural": "Caixas do Hub",
                "ordering": ("codigo", "retaguarda_id"),
            },
        ),
        migrations.AddConstraint(
            model_name="caixahub",
            constraint=models.UniqueConstraint(
                fields=("hub", "retaguarda_id"),
                name="uniq_caixa_hub_por_retaguarda",
            ),
        ),
        migrations.AddIndex(
            model_name="caixahub",
            index=models.Index(fields=("hub", "ativo"), name="idx_caixa_hub_ativo"),
        ),
    ]
