# Generated by Django 4.2.11 on 2026-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hubconfig_bootstrap_caixahub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('hub', 'codigo'), name='uniq_terminal_hub_codigo'),
        ),
    ]
