# Generated by Django 4.2.11 on 2026-09-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_terminal_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='pareado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='terminal',
            name='token_prefixo',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.CreateModel(
            name='PareamentoTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_hash', models.CharField(db_index=True, max_length=64)),
                ('codigo_prefixo', models.CharField(max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareamentos', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Pareamento de Terminal',
                'verbose_name_plural': 'Pareamentos de Terminal',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['terminal', 'usado_em', 'revogado_em'], name='idx_pareamento_terminal_ativo')],
            },
        ),
    ]
