# Generated by Django 4.2.11 on 2026-09-12 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_terminal_pareado_em_terminal_token_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='catalogo_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='catalogo_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='catalogo_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='tabela_preco_codigo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='tabela_preco_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='tabela_preco_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CatalogoItemHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_produto_id', models.PositiveBigIntegerField()),
                ('retaguarda_sku_id', models.PositiveBigIntegerField()),
                ('tipo_produto', models.CharField(max_length=30)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('descricao', models.CharField(max_length=200)),
                ('descricao_reduzida', models.CharField(blank=True, default='', max_length=120)),
                ('ean13', models.CharField(blank=True, db_index=True, default='', max_length=13)),
                ('codigo_item_ref', models.CharField(blank=True, default='', max_length=80)),
                ('cor_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cor_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('tamanho_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tamanho_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('unidade_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('unidade_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('unidade_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('preco', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('estoque_fisico', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserva', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('estoque_disponivel', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('vendavel', models.BooleanField(default=False)),
                ('motivos_bloqueio', models.JSONField(blank=True, default=list)),
                ('fiscal', models.JSONField(blank=True, default=dict)),
                ('ativo', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogo_itens', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Item de catálogo do Hub',
                'verbose_name_plural': 'Itens de catálogo do Hub',
                'ordering': ('descricao', 'retaguarda_sku_id'),
                'indexes': [models.Index(fields=['hub', 'ativo'], name='idx_catalogo_hub_ativo'), models.Index(fields=['hub', 'vendavel'], name='idx_catalogo_hub_vendavel'), models.Index(fields=['hub', 'referencia'], name='idx_catalogo_hub_ref')],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogoitemhub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_sku_id'), name='uniq_catalogo_hub_sku'),
        ),
    ]
