# Generated by Django 4.2.11 on 2026-09-13 14:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hubconfig_catalogo_gerado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='operadores_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='operadores_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='operadores_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OperadorHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_usuario_id', models.PositiveBigIntegerField()),
                ('codigo', models.CharField(db_index=True, max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=30)),
                ('perfil_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('perfil_nome', models.CharField(blank=True, default='', max_length=150)),
                ('credencial_hash', models.CharField(blank=True, default='', max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operadores', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Operador do Hub',
                'verbose_name_plural': 'Operadores do Hub',
                'ordering': ('codigo', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='SessaoOperadorHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_prefixo', models.CharField(blank=True, default='', max_length=12)),
                ('ativa', models.BooleanField(db_index=True, default=True)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade_em', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_encerramento', models.CharField(blank=True, default='', max_length=30)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.operadorhub')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_operador', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Sessão de operador do Hub',
                'verbose_name_plural': 'Sessões de operador do Hub',
                'ordering': ('-iniciada_em',),
                'indexes': [models.Index(fields=['terminal', 'ativa'], name='idx_sessao_oper_terminal'), models.Index(fields=['operador', 'ativa'], name='idx_sessao_oper_operador')],
            },
        ),
        migrations.AddIndex(
            model_name='operadorhub',
            index=models.Index(fields=['hub', 'ativo'], name='idx_operador_hub_ativo'),
        ),
        migrations.AddIndex(
            model_name='operadorhub',
            index=models.Index(fields=['hub', 'codigo'], name='idx_operador_hub_codigo'),
        ),
        migrations.AddConstraint(
            model_name='operadorhub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_usuario_id'), name='uniq_operador_hub_usuario'),
        ),
        migrations.AddConstraint(
            model_name='operadorhub',
            constraint=models.UniqueConstraint(fields=('hub', 'codigo'), name='uniq_operador_hub_codigo'),
        ),
    ]
