# Generated by Django 4.2.11 on 2026-09-13 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_hubconfig_operadores_gerado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoCaixaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('chave_caixa_aberto', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aberto_em', models.DateTimeField()),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='core.caixahub')),
                ('operador_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_abertura', to='core.operadorhub')),
                ('operador_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_fechamento', to='core.operadorhub')),
                ('sessao_operador_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_abertura', to='core.sessaooperadorhub')),
                ('sessao_operador_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_fechamento', to='core.sessaooperadorhub')),
                ('terminal_abertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_abertura', to='core.terminal')),
                ('terminal_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessoes_caixa_fechamento', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Sessão de caixa do Hub',
                'verbose_name_plural': 'Sessões de caixa do Hub',
                'ordering': ('-aberto_em',),
                'indexes': [models.Index(fields=['caixa', 'status'], name='idx_sessao_caixa_status'), models.Index(fields=['aberto_em'], name='idx_sessao_caixa_aberto'), models.Index(fields=['terminal_abertura'], name='idx_sessao_caixa_term_ab'), models.Index(fields=['operador_abertura'], name='idx_sessao_caixa_oper_ab')],
            },
        ),
    ]
