# Generated by Django 4.2.11 on 2026-09-13 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sessaocaixahub'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=12)),
                ('chave_venda_aberta_terminal', models.PositiveBigIntegerField(blank=True, null=True, unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto_itens', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('desconto_geral', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cliente_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=150)),
                ('vendedor_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('vendedor_nome', models.CharField(blank=True, default='', max_length=150)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.hubconfig')),
                ('operador_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_canceladas', to='core.operadorhub')),
                ('operador_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_criadas', to='core.operadorhub')),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.sessaocaixahub')),
                ('sessao_operador_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_canceladas', to='core.sessaooperadorhub')),
                ('sessao_operador_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_criadas', to='core.sessaooperadorhub')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.terminal')),
                ('terminal_cancelamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_canceladas', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Venda do Hub',
                'verbose_name_plural': 'Vendas do Hub',
                'ordering': ('-criada_em',),
            },
        ),
        migrations.CreateModel(
            name='VendaEventoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENDA_CRIADA', 'Venda criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_QUANTIDADE_ALTERADA', 'Item alterado'), ('ITEM_REMOVIDO', 'Item removido'), ('VENDA_CANCELADA', 'Venda cancelada')], max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venda', to='core.operadorhub')),
                ('sessao_operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venda', to='core.sessaooperadorhub')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_venda', to='core.terminal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.vendahub')),
            ],
            options={
                'verbose_name': 'Evento de venda do Hub',
                'verbose_name_plural': 'Eventos de venda do Hub',
                'ordering': ('criado_em', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VendaItemHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('retaguarda_produto_id', models.PositiveBigIntegerField()),
                ('retaguarda_sku_id', models.PositiveBigIntegerField()),
                ('ean13', models.CharField(blank=True, default='', max_length=13)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('codigo_item_ref', models.CharField(blank=True, default='', max_length=80)),
                ('descricao', models.CharField(max_length=200)),
                ('descricao_reduzida', models.CharField(blank=True, default='', max_length=120)),
                ('cor_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('tamanho_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('unidade_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=18)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('catalogo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venda_itens', to='core.catalogoitemhub')),
                ('operador_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venda_itens_incluidos', to='core.operadorhub')),
                ('sessao_operador_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venda_itens_incluidos', to='core.sessaooperadorhub')),
                ('terminal_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venda_itens_incluidos', to='core.terminal')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.vendahub')),
            ],
            options={
                'verbose_name': 'Item de venda do Hub',
                'verbose_name_plural': 'Itens de venda do Hub',
                'ordering': ('criado_em', 'id'),
                'indexes': [models.Index(fields=['venda', 'retaguarda_sku_id'], name='idx_venda_item_sku'), models.Index(fields=['retaguarda_sku_id'], name='idx_venda_item_sku_global')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendaitemhub',
            constraint=models.UniqueConstraint(fields=('venda', 'retaguarda_sku_id'), name='uniq_venda_hub_sku'),
        ),
        migrations.AddIndex(
            model_name='vendahub',
            index=models.Index(fields=['hub', 'status'], name='idx_venda_hub_status'),
        ),
        migrations.AddIndex(
            model_name='vendahub',
            index=models.Index(fields=['terminal', 'status'], name='idx_venda_terminal_status'),
        ),
        migrations.AddIndex(
            model_name='vendahub',
            index=models.Index(fields=['sessao_caixa', 'status'], name='idx_venda_caixa_status'),
        ),
        migrations.AddIndex(
            model_name='vendaeventohub',
            index=models.Index(fields=['venda', 'tipo'], name='idx_venda_evento_tipo'),
        ),
        migrations.AddIndex(
            model_name='vendaeventohub',
            index=models.Index(fields=['criado_em'], name='idx_venda_evento_criado'),
        ),
    ]
