# Generated by Django 4.2.11 on 2026-09-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendahub_vendaeventohub_vendaitemhub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamentoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_id', models.PositiveBigIntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=24)),
                ('num_parcelas', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('prazo_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('prazo_codigo', models.CharField(blank=True, default='', max_length=12)),
                ('prazo_descricao', models.CharField(blank=True, default='', max_length=120)),
                ('prazo_num_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('prazo_intervalo_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('adquirente', models.CharField(blank=True, max_length=80, null=True)),
                ('conta_liquidacao_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gera_recebivel_bancario', models.BooleanField(default=False)),
                ('prazo_credito_dias', models.PositiveIntegerField(default=0)),
                ('taxa_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tef_habilitado', models.BooleanField(default=False)),
                ('tef_modalidade', models.CharField(blank=True, default='', max_length=20)),
                ('tef_adquirente_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('tef_terminal_logico', models.CharField(blank=True, default='', max_length=40)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forma de pagamento do Hub',
                'verbose_name_plural': 'Formas de pagamento do Hub',
                'ordering': ('codigo', 'retaguarda_id'),
            },
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='formas_pagamento_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='formas_pagamento_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='formas_pagamento_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormaPagamentoParcelaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('dias', models.IntegerField()),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.formapagamentohub')),
            ],
            options={
                'verbose_name': 'Parcela de forma de pagamento do Hub',
                'verbose_name_plural': 'Parcelas de formas de pagamento do Hub',
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.AddField(
            model_name='formapagamentohub',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento', to='core.hubconfig'),
        ),
        migrations.AddConstraint(
            model_name='formapagamentoparcelahub',
            constraint=models.UniqueConstraint(fields=('forma', 'ordem'), name='uniq_fpg_parc_ord'),
        ),
        migrations.AddIndex(
            model_name='formapagamentohub',
            index=models.Index(fields=['hub', 'ativo'], name='idx_fpg_hub_ativo'),
        ),
        migrations.AddConstraint(
            model_name='formapagamentohub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_fpg_hub_ret'),
        ),
        migrations.AddConstraint(
            model_name='formapagamentohub',
            constraint=models.UniqueConstraint(fields=('hub', 'codigo'), name='uniq_fpg_hub_cod'),
        ),
    ]
