# Generated by Django 4.2.11 on 2026-09-14 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_formapagamentohub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaPagamentoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('operacao_uuid', models.UUIDField(editable=False)),
                ('retaguarda_forma_pagamento_id', models.PositiveBigIntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=24)),
                ('num_parcelas', models.PositiveIntegerField()),
                ('adquirente', models.CharField(blank=True, max_length=80, null=True)),
                ('conta_liquidacao_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gera_recebivel_bancario', models.BooleanField(default=False)),
                ('prazo_credito_dias', models.PositiveIntegerField(default=0)),
                ('taxa_percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('autorizacao', models.CharField(blank=True, default='', max_length=120)),
                ('origem_captura', models.CharField(choices=[('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('REMOVIDO', 'Removido')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('removido_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_venda', to='core.formapagamentohub')),
                ('operador_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_incluidos', to='core.operadorhub')),
                ('operador_remocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_removidos', to='core.operadorhub')),
                ('sessao_operador_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_incluidos', to='core.sessaooperadorhub')),
                ('sessao_operador_remocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_removidos', to='core.sessaooperadorhub')),
                ('terminal_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_incluidos', to='core.terminal')),
                ('terminal_remocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_removidos', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Pagamento de venda do Hub',
                'verbose_name_plural': 'Pagamentos de venda do Hub',
                'ordering': ('criado_em', 'id'),
            },
        ),
        migrations.AddField(
            model_name='vendahub',
            name='finalizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='operador_finalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_finalizadas', to='core.operadorhub'),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='sessao_operador_finalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_finalizadas', to='core.sessaooperadorhub'),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='terminal_finalizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_finalizadas', to='core.terminal'),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='vendaeventohub',
            name='tipo',
            field=models.CharField(choices=[('VENDA_CRIADA', 'Venda criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_QUANTIDADE_ALTERADA', 'Item alterado'), ('ITEM_REMOVIDO', 'Item removido'), ('VENDA_CANCELADA', 'Venda cancelada'), ('PAGAMENTO_ADICIONADO', 'Pagamento adicionado'), ('PAGAMENTO_REMOVIDO', 'Pagamento removido'), ('VENDA_FINALIZADA', 'Venda finalizada')], max_length=40),
        ),
        migrations.CreateModel(
            name='VendaPagamentoParcelaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('dias', models.IntegerField()),
                ('percentual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_snapshot', to='core.vendapagamentohub')),
            ],
            options={
                'verbose_name': 'Parcela snapshot de pagamento do Hub',
                'verbose_name_plural': 'Parcelas snapshot de pagamento do Hub',
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.AddField(
            model_name='vendapagamentohub',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='core.vendahub'),
        ),
        migrations.CreateModel(
            name='EstoqueMovimentoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('retaguarda_produto_id', models.PositiveBigIntegerField()),
                ('retaguarda_sku_id', models.PositiveBigIntegerField()),
                ('ean13', models.CharField(blank=True, default='', max_length=13)),
                ('referencia', models.CharField(blank=True, default='', max_length=80)),
                ('tipo', models.CharField(choices=[('SAIDA_VENDA', 'Saída por venda')], default='SAIDA_VENDA', max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sincronizado_central_em', models.DateTimeField(blank=True, null=True)),
                ('reconciliado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('catalogo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.catalogoitemhub')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.hubconfig')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.vendahub')),
                ('venda_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_estoque', to='core.vendaitemhub')),
            ],
            options={
                'verbose_name': 'Movimento de estoque do Hub',
                'verbose_name_plural': 'Movimentos de estoque do Hub',
                'ordering': ('criado_em', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='vendapagamentoparcelahub',
            constraint=models.UniqueConstraint(fields=('pagamento', 'ordem'), name='uniq_vpag_parc_ord'),
        ),
        migrations.AddConstraint(
            model_name='vendapagamentohub',
            constraint=models.UniqueConstraint(fields=('venda', 'operacao_uuid'), name='uniq_vpag_oper'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentohub',
            index=models.Index(fields=['hub', 'retaguarda_sku_id'], name='idx_est_mov_hub_sku'),
        ),
        migrations.AddIndex(
            model_name='estoquemovimentohub',
            index=models.Index(fields=['reconciliado_em'], name='idx_est_mov_reconc'),
        ),
        migrations.AddConstraint(
            model_name='estoquemovimentohub',
            constraint=models.UniqueConstraint(fields=('venda_item',), name='uniq_est_mov_item'),
        ),
    ]
