# Generated by Django 4.2.11 on 2026-09-14 21:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vendapagamentohub_vendahub_finalizada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='clientes_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='clientes_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='clientes_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClienteHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('RETAGUARDA', 'Retaguarda'), ('LOCAL', 'Local')], default='RETAGUARDA', max_length=20)),
                ('presente_retaguarda', models.BooleanField(default=False)),
                ('tipo_pessoa', models.CharField(max_length=2)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_padrao', models.BooleanField(default=False)),
                ('nome_cliente', models.CharField(max_length=150)),
                ('apelido', models.CharField(blank=True, default='', max_length=100)),
                ('endereco', models.CharField(blank=True, default='', max_length=150)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('cep', models.CharField(blank=True, default='', max_length=12)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('telefone1', models.CharField(blank=True, default='', max_length=30)),
                ('telefone2', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('categoria', models.CharField(blank=True, default='', max_length=80)),
                ('bloqueio', models.BooleanField(default=False)),
                ('motivo_bloqueio', models.CharField(blank=True, max_length=200, null=True)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('mala_direta', models.BooleanField(default=False)),
                ('aceita_email', models.BooleanField(default=False)),
                ('aceita_whatsapp', models.BooleanField(default=False)),
                ('aceita_sms', models.BooleanField(default=False)),
                ('consentimento_em', models.DateTimeField(blank=True, null=True)),
                ('origem_consentimento', models.CharField(blank=True, default='', max_length=80)),
                ('ativo', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Cliente do Hub',
                'verbose_name_plural': 'Clientes do Hub',
                'ordering': ('nome_cliente', 'retaguarda_id', 'cliente_uuid'),
                'indexes': [models.Index(fields=['hub', 'presente_retaguarda'], name='idx_cli_hub_pres'), models.Index(fields=['hub', 'origem'], name='idx_cli_hub_origem'), models.Index(fields=['hub', 'nome_cliente'], name='idx_cli_hub_nome')],
            },
        ),
        migrations.AddConstraint(
            model_name='clientehub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_cliente_hub_ret'),
        ),
        migrations.AddConstraint(
            model_name='clientehub',
            constraint=models.UniqueConstraint(fields=('hub', 'documento'), name='uniq_cliente_hub_doc'),
        ),
    ]
