# Generated by Django 4.2.11 on 2026-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hubconfig_clientes_gerado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendahub',
            name='cliente_documento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='cliente_padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='cliente_tipo_pessoa',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='cliente_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendaeventohub',
            name='tipo',
            field=models.CharField(choices=[('VENDA_CRIADA', 'Venda criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_QUANTIDADE_ALTERADA', 'Item alterado'), ('ITEM_REMOVIDO', 'Item removido'), ('VENDA_CANCELADA', 'Venda cancelada'), ('PAGAMENTO_ADICIONADO', 'Pagamento adicionado'), ('PAGAMENTO_REMOVIDO', 'Pagamento removido'), ('VENDA_FINALIZADA', 'Venda finalizada'), ('CLIENTE_SELECIONADO', 'Cliente selecionado'), ('CLIENTE_REMOVIDO', 'Cliente removido')], max_length=40),
        ),
    ]
