# Generated by Django 4.2.11 on 2026-09-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vendahub_cliente_documento_vendahub_cliente_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoVendaTerminalHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente_preselecionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextos_pre_venda', to='core.clientehub')),
                ('terminal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contexto_venda', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Contexto de venda do terminal Hub',
                'verbose_name_plural': 'Contextos de venda dos terminais Hub',
            },
        ),
    ]
