# Generated by Django 4.2.11 on 2026-09-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contextovendaterminalhub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientehub',
            name='sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
