# Generated by Django 4.2.11 on 2026-09-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_clientehub_sincronizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='vendedores_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='vendedores_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='vendedores_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendedorHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_id', models.PositiveBigIntegerField()),
                ('matricula', models.CharField(blank=True, default='', max_length=6)),
                ('nome', models.CharField(max_length=50)),
                ('apelido', models.CharField(blank=True, default='', max_length=20)),
                ('cargo_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cargo_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('cargo_descricao', models.CharField(blank=True, default='', max_length=80)),
                ('comissionado', models.BooleanField(default=False)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ativo', models.BooleanField(default=True)),
                ('situacao', models.CharField(max_length=12)),
                ('participa_vendas', models.BooleanField(default=False)),
                ('presente_retaguarda', models.BooleanField(default=False)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedores', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Vendedor do Hub',
                'verbose_name_plural': 'Vendedores do Hub',
                'ordering': ('nome', 'retaguarda_id'),
                'indexes': [models.Index(fields=['hub', 'presente_retaguarda'], name='idx_vend_hub_pres'), models.Index(fields=['hub', 'nome'], name='idx_vend_hub_nome'), models.Index(fields=['hub', 'matricula'], name='idx_vend_hub_mat')],
            },
        ),
        migrations.AddConstraint(
            model_name='vendedorhub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_vendedor_hub_ret'),
        ),
    ]
