# Generated by Django 4.2.11 on 2026-09-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hubconfig_vendedores_gerado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextovendaterminalhub',
            name='vendedor_preselecionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextos_pre_venda', to='core.vendedorhub'),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_apelido',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_cargo_codigo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_cargo_descricao',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_cargo_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_comissionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendahub',
            name='vendedor_matricula',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='vendaeventohub',
            name='tipo',
            field=models.CharField(choices=[('VENDA_CRIADA', 'Venda criada'), ('ITEM_ADICIONADO', 'Item adicionado'), ('ITEM_QUANTIDADE_ALTERADA', 'Item alterado'), ('ITEM_REMOVIDO', 'Item removido'), ('VENDA_CANCELADA', 'Venda cancelada'), ('PAGAMENTO_ADICIONADO', 'Pagamento adicionado'), ('PAGAMENTO_REMOVIDO', 'Pagamento removido'), ('VENDA_FINALIZADA', 'Venda finalizada'), ('CLIENTE_SELECIONADO', 'Cliente selecionado'), ('CLIENTE_REMOVIDO', 'Cliente removido'), ('VENDEDOR_SELECIONADO', 'Vendedor selecionado'), ('VENDEDOR_REMOVIDO', 'Vendedor removido')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vendahub',
            name='vendedor_nome',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
