# Generated by Django 4.2.11 on 2026-09-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contextovendaterminalhub_vendedor_preselecionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubconfig',
            name='tipos_despesa_pdv_gerado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='tipos_despesa_pdv_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hubconfig',
            name='tipos_despesa_pdv_versao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TipoDespesaPdvHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_id', models.PositiveBigIntegerField()),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=120)),
                ('exige_documento', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('presente_retaguarda', models.BooleanField(default=False)),
                ('natureza_retaguarda_id', models.PositiveBigIntegerField()),
                ('natureza_codigo', models.CharField(max_length=10)),
                ('natureza_descricao', models.CharField(max_length=255)),
                ('natureza_categoria_principal', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_subcategoria', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_tipo', models.CharField(max_length=20)),
                ('natureza_status', models.CharField(max_length=10)),
                ('natureza_tipo_natureza', models.CharField(max_length=10)),
                ('natureza_operacao', models.CharField(max_length=20)),
                ('natureza_categoria_gerencial', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_movimenta_financeiro', models.BooleanField(default=True)),
                ('natureza_entra_dre', models.BooleanField(default=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_despesa_pdv', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Tipo de despesa PDV do Hub',
                'verbose_name_plural': 'Tipos de despesa PDV do Hub',
                'ordering': ('descricao', 'codigo', 'retaguarda_id'),
                'indexes': [models.Index(fields=['hub', 'presente_retaguarda'], name='idx_tipo_desp_pdv_pres'), models.Index(fields=['hub', 'ativo'], name='idx_tipo_desp_pdv_ativo'), models.Index(fields=['hub', 'codigo'], name='idx_tipo_desp_pdv_cod')],
            },
        ),
        migrations.AddConstraint(
            model_name='tipodespesapdvhub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_tipo_desp_pdv_hub_ret'),
        ),
    ]
