# Generated by Django 4.2.11 on 2026-09-16 22:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_corrige_tamanho_natureza_tipo_despesa_pdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoCaixaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimento_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('SANGRIA', 'Sangria'), ('SUPRIMENTO', 'Suprimento')], max_length=12)),
                ('status', models.CharField(choices=[('EFETIVA', 'Efetiva')], default='EFETIVA', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento', models.CharField(blank=True, default='', max_length=80)),
                ('historico', models.CharField(blank=True, default='', max_length=200)),
                ('ocorrido_em', models.DateTimeField()),
                ('tipo_despesa_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_despesa_codigo', models.CharField(blank=True, default='', max_length=20)),
                ('tipo_despesa_descricao', models.CharField(blank=True, default='', max_length=120)),
                ('tipo_despesa_exige_documento', models.BooleanField(blank=True, null=True)),
                ('natureza_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('natureza_codigo', models.CharField(blank=True, default='', max_length=10)),
                ('natureza_descricao', models.CharField(blank=True, default='', max_length=255)),
                ('natureza_categoria_principal', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_subcategoria', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_tipo', models.CharField(blank=True, default='', max_length=20)),
                ('natureza_status', models.CharField(blank=True, default='', max_length=10)),
                ('natureza_tipo_natureza', models.CharField(blank=True, default='', max_length=10)),
                ('natureza_operacao', models.CharField(blank=True, default='', max_length=20)),
                ('natureza_categoria_gerencial', models.CharField(blank=True, default='', max_length=50)),
                ('natureza_movimenta_financeiro', models.BooleanField(blank=True, null=True)),
                ('natureza_entra_dre', models.BooleanField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.caixahub')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='core.hubconfig')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='core.operadorhub')),
                ('sessao_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='core.sessaocaixahub')),
                ('sessao_operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='core.sessaooperadorhub')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_caixa', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Movimentação de caixa do Hub',
                'verbose_name_plural': 'Movimentações de caixa do Hub',
                'ordering': ('ocorrido_em', 'id'),
                'indexes': [models.Index(fields=['hub', 'tipo'], name='idx_mov_cx_hub_tipo'), models.Index(fields=['sessao_caixa', 'ocorrido_em', 'id'], name='idx_mov_cx_sessao_ord'), models.Index(fields=['caixa', 'status'], name='idx_mov_cx_caixa_status'), models.Index(fields=['movimento_uuid'], name='idx_mov_cx_uuid')],
            },
        ),
    ]
