# Generated by Django 4.2.11 on 2026-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_movimentacao_caixa_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaocaixahub',
            name='diferenca_fechamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessaocaixahub',
            name='observacao_fechamento',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sessaocaixahub',
            name='resumo_fechamento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessaocaixahub',
            name='situacao_fechamento',
            field=models.CharField(blank=True, choices=[('OK', 'Ok'), ('SOBRA', 'Sobra'), ('FALTA', 'Falta')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='sessaocaixahub',
            name='valor_contado_fechamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sessaocaixahub',
            name='valor_esperado_fechamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
