# Generated by Django 4.2.11 on 2026-09-17 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sessaocaixahub_diferenca_fechamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoDiaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechamento_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_operacional', models.DateField()),
                ('quantidade_vendas', models.PositiveIntegerField(default=0)),
                ('total_vendas', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_conferido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferenca_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('situacao', models.CharField(choices=[('OK', 'Ok'), ('DIVERGENTE', 'Divergente')], max_length=12)),
                ('fechado_em', models.DateTimeField()),
                ('observacao', models.TextField(blank=True, default='')),
                ('resumo_snapshot', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dia', to='core.hubconfig')),
                ('operador_fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dia', to='core.operadorhub')),
                ('terminal_fechamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_dia', to='core.terminal')),
            ],
            options={
                'verbose_name': 'Fechamento diário do Hub',
                'verbose_name_plural': 'Fechamentos diários do Hub',
                'ordering': ('-data_operacional', '-fechado_em'),
            },
        ),
        migrations.CreateModel(
            name='FechamentoDiaFormaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=24)),
                ('descricao', models.CharField(max_length=120)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('valor_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_conferido', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('situacao', models.CharField(choices=[('OK', 'Ok'), ('SOBRA', 'Sobra'), ('FALTA', 'Falta')], max_length=5)),
                ('detalhes_snapshot', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formas', to='core.fechamentodiahub')),
            ],
            options={
                'verbose_name': 'Forma do fechamento diário do Hub',
                'verbose_name_plural': 'Formas do fechamento diário do Hub',
                'ordering': ('tipo',),
            },
        ),
        migrations.AddIndex(
            model_name='fechamentodiahub',
            index=models.Index(fields=['hub', 'data_operacional'], name='idx_fech_dia_hub_data'),
        ),
        migrations.AddIndex(
            model_name='fechamentodiahub',
            index=models.Index(fields=['fechado_em'], name='idx_fech_dia_fechado'),
        ),
        migrations.AddConstraint(
            model_name='fechamentodiahub',
            constraint=models.UniqueConstraint(fields=('hub', 'data_operacional'), name='uniq_fech_dia_hub_data'),
        ),
        migrations.AddConstraint(
            model_name='fechamentodiaformahub',
            constraint=models.UniqueConstraint(fields=('fechamento', 'tipo'), name='uniq_fech_dia_forma_tipo'),
        ),
    ]
