# Generated by Django 4.2.11 on 2026-09-20 14:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_catalogoitemhub_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitemhub',
            name='fiscal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='NFCeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfce_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modelo', models.CharField(default='65', max_length=2)),
                ('ambiente', models.CharField(max_length=12)),
                ('serie', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('codigo_numerico', models.CharField(max_length=8)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('chave_acesso', models.CharField(db_index=True, max_length=44, unique=True)),
                ('tipo_emissao', models.CharField(default='1', max_length=1)),
                ('status', models.CharField(choices=[('GERANDO', 'Gerando'), ('GERADA', 'Gerada'), ('ERRO_GERACAO', 'Erro de geração'), ('PENDENTE_TRANSMISSAO', 'Pendente transmissão'), ('AUTORIZADA', 'Autorizada'), ('REJEITADA', 'Rejeitada'), ('CONTINGENCIA', 'Contingência'), ('CANCELADA', 'Cancelada')], db_index=True, default='GERANDO', max_length=24)),
                ('xml_sem_assinatura', models.TextField(blank=True, default='')),
                ('xml_assinado', models.TextField(blank=True, default='')),
                ('qr_code_payload', models.TextField(blank=True, default='')),
                ('protocolo', models.CharField(blank=True, default='', max_length=60)),
                ('codigo_retorno', models.CharField(blank=True, default='', max_length=10)),
                ('mensagem_retorno', models.CharField(blank=True, default='', max_length=255)),
                ('emitida_em', models.DateTimeField()),
                ('autorizada_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfces', to='core.hubconfig')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nfce', to='core.vendahub')),
            ],
            options={
                'verbose_name': 'NFC-e do Hub',
                'verbose_name_plural': 'NFC-es do Hub',
                'ordering': ('-emitida_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FormaPagamentoFiscalMapHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento_retaguarda_id', models.PositiveBigIntegerField()),
                ('codigo_tpag', models.CharField(max_length=2)),
                ('descricao_fiscal', models.CharField(blank=True, default='', max_length=80)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formas_pagamento_fiscais', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Mapa fiscal de forma de pagamento do Hub',
                'verbose_name_plural': 'Mapas fiscais de formas de pagamento do Hub',
                'ordering': ('forma_pagamento_retaguarda_id', 'codigo_tpag', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscalHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emite_nfce', models.BooleanField(default=False)),
                ('ambiente_fiscal', models.CharField(blank=True, default='', max_length=12)),
                ('regime_tributario', models.CharField(blank=True, default='', max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=20)),
                ('serie_nfce', models.PositiveIntegerField(default=1)),
                ('proximo_numero_nfce', models.PositiveIntegerField(default=1)),
                ('razao_social', models.CharField(blank=True, default='', max_length=120)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=120)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('logradouro', models.CharField(blank=True, default='', max_length=50)),
                ('endereco', models.CharField(blank=True, default='', max_length=80)),
                ('numero', models.CharField(blank=True, default='', max_length=10)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=40)),
                ('cidade', models.CharField(blank=True, default='', max_length=50)),
                ('uf', models.CharField(blank=True, default='', max_length=2)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('codigo_municipio_ibge', models.CharField(blank=True, default='', max_length=7)),
                ('sincronizado_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuracao_fiscal', to='core.hubconfig')),
            ],
            options={
                'verbose_name': 'Configuração fiscal do Hub',
                'verbose_name_plural': 'Configurações fiscais do Hub',
            },
        ),
        migrations.AddConstraint(
            model_name='nfcehub',
            constraint=models.UniqueConstraint(fields=('hub', 'serie', 'numero'), name='uniq_nfce_hub_serie_numero'),
        ),
        migrations.AddIndex(
            model_name='formapagamentofiscalmaphub',
            index=models.Index(fields=['hub', 'forma_pagamento_retaguarda_id'], name='idx_fpg_fiscal_hub_forma'),
        ),
        migrations.AddConstraint(
            model_name='formapagamentofiscalmaphub',
            constraint=models.UniqueConstraint(fields=('hub', 'forma_pagamento_retaguarda_id', 'codigo_tpag'), name='uniq_fpg_fiscal_hub_forma_tpag'),
        ),
    ]
