# Generated by Django 4.2.11 on 2026-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_vendaitemhub_fiscal_nfcehub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcehub',
            name='entrada_contingencia_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcehub',
            name='justificativa_contingencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
