# Generated by Codex on 2026-09-20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_nfcehub_entrada_contingencia_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfcehub",
            name="xml_autorizado",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="nfcehub",
            name="sync_versao",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EventoSyncHub",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evento_uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("chave_idempotencia", models.CharField(max_length=120)),
                ("tipo", models.CharField(db_index=True, max_length=40)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("PENDENTE", "Pendente"), ("PROCESSANDO", "Processando"), ("SINCRONIZADO", "Sincronizado"), ("ERRO", "Erro"), ("CONFLITO", "Conflito")], db_index=True, default="PENDENTE", max_length=14)),
                ("tentativas", models.PositiveIntegerField(default=0)),
                ("proxima_tentativa_em", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ultimo_erro", models.CharField(blank=True, default="", max_length=255)),
                ("resposta", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("sincronizado_em", models.DateTimeField(blank=True, null=True)),
                ("hub", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eventos_sync", to="core.hubconfig")),
            ],
            options={
                "verbose_name": "Evento de sincronização do Hub",
                "verbose_name_plural": "Eventos de sincronização do Hub",
                "ordering": ("criado_em", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="eventosynchub",
            constraint=models.UniqueConstraint(fields=("hub", "evento_uuid"), name="uniq_evt_sync_hub_uuid"),
        ),
        migrations.AddConstraint(
            model_name="eventosynchub",
            constraint=models.UniqueConstraint(fields=("hub", "chave_idempotencia"), name="uniq_evt_sync_hub_chave"),
        ),
        migrations.AddIndex(
            model_name="eventosynchub",
            index=models.Index(fields=["hub", "status", "criado_em"], name="idx_evt_sync_hub_status"),
        ),
        migrations.AddIndex(
            model_name="eventosynchub",
            index=models.Index(fields=["proxima_tentativa_em"], name="idx_evt_sync_prox"),
        ),
    ]
