# Generated by Django 4.2.11 on 2026-09-20 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_eventosynchub_nfce_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValeTrocaHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cliente_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cliente_retaguarda_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('documento', models.CharField(max_length=80)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='ABERTO', max_length=12)),
                ('validade', models.DateField(blank=True, null=True)),
                ('origem_devolucao_uuid', models.UUIDField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='VendaDevolucaoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolucao_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cliente_uuid', models.UUIDField(blank=True, null=True)),
                ('cliente_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(default='FINALIZADA', max_length=12)),
                ('finalizada_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.hubconfig')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.operadorhub')),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.terminal')),
                ('venda_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.vendahub')),
            ],
            options={
                'ordering': ('-finalizada_em', '-id'),
            },
        ),
        migrations.AddField(
            model_name='vendaitemhub',
            name='promocao_acumula_cashback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendaitemhub',
            name='promocao_nome',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='vendaitemhub',
            name='promocao_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendaitemhub',
            name='promocao_tipo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendaitemhub',
            name='promocao_valor',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='vendapagamentohub',
            name='vale_troca_documento',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vendapagamentohub',
            name='vale_troca_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendaDevolucaoItemHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_produto_id', models.PositiveBigIntegerField()),
                ('retaguarda_sku_id', models.PositiveBigIntegerField()),
                ('ean13', models.CharField(blank=True, default='', max_length=13)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=4, max_digits=18)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=18)),
                ('catalogo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.catalogoitemhub')),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='core.vendadevolucaohub')),
                ('venda_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.vendaitemhub')),
            ],
        ),
        migrations.CreateModel(
            name='ValeTrocaMovimentoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('saldo_apos', models.DecimalField(decimal_places=2, max_digits=18)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.valetrocahub')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_troca_movimentos', to='core.vendahub')),
            ],
        ),
        migrations.AddField(
            model_name='valetrocahub',
            name='devolucao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vale_troca', to='core.vendadevolucaohub'),
        ),
        migrations.AddField(
            model_name='valetrocahub',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales_troca', to='core.hubconfig'),
        ),
        migrations.CreateModel(
            name='PromocaoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_id', models.PositiveBigIntegerField()),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('produto_retaguarda_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sku_retaguarda_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('acumula_cashback', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=0)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promocoes', to='core.hubconfig')),
            ],
            options={
                'ordering': ('prioridade', 'retaguarda_id'),
            },
        ),
        migrations.CreateModel(
            name='CashbackMovimentoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_uuid', models.UUIDField(blank=True, db_index=True, null=True)),
                ('cliente_retaguarda_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('tipo', models.CharField(max_length=10)),
                ('status', models.CharField(default='ATIVO', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=18)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_movimentos', to='core.hubconfig')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashback_movimentos', to='core.vendahub')),
            ],
            options={
                'ordering': ('-criado_em', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashbackConfigHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_id', models.PositiveBigIntegerField()),
                ('nome', models.CharField(default='Regra padrão', max_length=80)),
                ('ativo', models.BooleanField(default=False)),
                ('percentual', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('validade_dias', models.PositiveIntegerField(default=180)),
                ('valor_minimo_geracao', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('valor_minimo_uso', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('limite_uso_percentual', models.DecimalField(decimal_places=4, default=100, max_digits=7)),
                ('consumidor_final_participa', models.BooleanField(default=False)),
                ('sincronizado_em', models.DateTimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashback_configs', to='core.hubconfig')),
            ],
            options={
                'ordering': ('-ativo', 'retaguarda_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='vendadevolucaoitemhub',
            constraint=models.UniqueConstraint(fields=('devolucao', 'venda_item'), name='uniq_dev_hub_item'),
        ),
        migrations.AddConstraint(
            model_name='valetrocahub',
            constraint=models.UniqueConstraint(fields=('hub', 'documento'), name='uniq_vale_hub_doc'),
        ),
        migrations.AddConstraint(
            model_name='promocaohub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_promo_hub_ret'),
        ),
        migrations.AddIndex(
            model_name='cashbackmovimentohub',
            index=models.Index(fields=['hub', 'cliente_retaguarda_id', 'status'], name='idx_cash_hub_cli_ret'),
        ),
        migrations.AddIndex(
            model_name='cashbackmovimentohub',
            index=models.Index(fields=['hub', 'cliente_uuid', 'status'], name='idx_cash_hub_cli_uuid'),
        ),
        migrations.AddConstraint(
            model_name='cashbackconfighub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_id'), name='uniq_cashback_cfg_hub_ret'),
        ),
    ]
