# Generated by Django 4.2.11 on 2026-09-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_valetrocahub_vendadevolucaohub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoitemhub',
            name='colecao_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogoitemhub',
            name='grupo_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogoitemhub',
            name='subgrupo_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocaohub',
            name='colecao_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promocaohub',
            name='escopo',
            field=models.CharField(default='TODOS', max_length=15),
        ),
        migrations.AddField(
            model_name='promocaohub',
            name='grupo_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promocaohub',
            name='produto_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='promocaohub',
            name='subgrupo_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
