# Generated by Django 4.2.11 on 2026-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_catalogoitemhub_colecao_retaguarda_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackmovimentohub',
            name='centralizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientehub',
            name='cashback_saldo_retaguarda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='clientehub',
            name='cashback_saldo_retaguarda_sincronizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
