# Generated by Django 4.2.11 on 2026-09-28 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_formapagamentohub_adquirente_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComandoAdministrativoRecebidoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retaguarda_comando_id', models.PositiveBigIntegerField()),
                ('tipo', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('mensagem_erro', models.CharField(blank=True, default='', max_length=500)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandos_administrativos_recebidos', to='core.hubconfig')),
            ],
            options={
                'ordering': ('-recebido_em', '-id'),
                'indexes': [models.Index(fields=['hub', 'status'], name='idx_cmd_admin_hub_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='comandoadministrativorecebidohub',
            constraint=models.UniqueConstraint(fields=('hub', 'retaguarda_comando_id'), name='uniq_cmd_admin_hub_ret'),
        ),
    ]
