# Generated by Django 4.2.11 on 2026-09-30 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_hubconfig_ultima_tentativa_central_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='confirmado_central_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='documento_central',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='loja_origem_nome',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='loja_origem_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='venda_origem_documento',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='vendadevolucaohub',
            name='venda_origem_retaguarda_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendadevolucaohub',
            name='venda_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.vendahub'),
        ),
        migrations.AlterField(
            model_name='vendadevolucaoitemhub',
            name='venda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to='core.vendaitemhub'),
        ),
    ]
