from django.urls import path

from core.api import (
    CaixaAbrirView,
    CaixaFecharView,
    CaixaMovimentacoesView,
    CaixaResumoView,
    CaixaStatusView,
    DevolucaoConsultarView,
    DevolucaoClienteVendasView,
    DevolucaoClientesView,
    DevolucaoFinalizarView,
    DevolucaoVendaCentralView,
    DevolucaoVendasView,
    FechamentoDiaView,
    FormasPagamentoView,
    OperadorContextoView,
    OperadorLoginView,
    OperadorLogoutView,
    ParearTerminalView,
    RecuperarTerminalLocalView,
    TerminalCatalogoView,
    TerminalCatalogoImagemView,
    TerminalCentralStatusView,
    TerminalClienteBeneficiosView,
    TerminalClientesView,
    TerminalContextoView,
    TerminalHeartbeatView,
    TerminalVendedoresView,
    TiposDespesaPdvView,
    ValeTrocaConsultarView,
    ValeTrocaPagamentoView,
    VendaAtualView,
    VendaCancelarView,
    VendaClienteView,
    VendaFinalizarView,
    VendaDanfeNFCeView,
    VendaIniciarView,
    VendaItemDetalheView,
    VendaItemView,
    VendaPagamentoDetalheView,
    VendaPagamentoView,
    VendaVendedorView,
)


urlpatterns = [
    path("parear/", ParearTerminalView.as_view(), name="terminal-parear"),
    path("recuperar-local/", RecuperarTerminalLocalView.as_view(), name="terminal-recuperar-local"),
    path("contexto/", TerminalContextoView.as_view(), name="terminal-contexto"),
    path("heartbeat/", TerminalHeartbeatView.as_view(), name="terminal-heartbeat"),
    path("central/status/", TerminalCentralStatusView.as_view(), name="terminal-central-status"),
    path("catalogo/", TerminalCatalogoView.as_view(), name="terminal-catalogo"),
    path("catalogo/imagens/<int:produto_id>/<str:versao>/", TerminalCatalogoImagemView.as_view(), name="terminal-catalogo-imagem"),
    path("clientes/", TerminalClientesView.as_view(), name="terminal-clientes"),
    path("clientes/<uuid:cliente_uuid>/beneficios/", TerminalClienteBeneficiosView.as_view(), name="terminal-cliente-beneficios"),
    path("vendedores/", TerminalVendedoresView.as_view(), name="terminal-vendedores"),
    path("tipos-despesa-pdv/", TiposDespesaPdvView.as_view(), name="terminal-tipos-despesa-pdv"),
    path("operador/login/", OperadorLoginView.as_view(), name="operador-login"),
    path("operador/contexto/", OperadorContextoView.as_view(), name="operador-contexto"),
    path("operador/logout/", OperadorLogoutView.as_view(), name="operador-logout"),
    path("caixa/status/", CaixaStatusView.as_view(), name="terminal-caixa-status"),
    path("caixa/abrir/", CaixaAbrirView.as_view(), name="terminal-caixa-abrir"),
    path("caixa/fechar/", CaixaFecharView.as_view(), name="terminal-caixa-fechar"),
    path("caixa/movimentacoes/", CaixaMovimentacoesView.as_view(), name="terminal-caixa-movimentacoes"),
    path("caixa/resumo/", CaixaResumoView.as_view(), name="terminal-caixa-resumo"),
    path("fechamento-dia/", FechamentoDiaView.as_view(), name="terminal-fechamento-dia"),
    path("formas-pagamento/", FormasPagamentoView.as_view(), name="terminal-formas-pagamento"),
    path("vale-troca/consultar/", ValeTrocaConsultarView.as_view(), name="terminal-vale-troca-consultar"),
    path("venda/atual/", VendaAtualView.as_view(), name="terminal-venda-atual"),
    path("venda/iniciar/", VendaIniciarView.as_view(), name="terminal-venda-iniciar"),
    path("venda/cliente/", VendaClienteView.as_view(), name="terminal-venda-cliente"),
    path("venda/vendedor/", VendaVendedorView.as_view(), name="terminal-venda-vendedor"),
    path("venda/item/", VendaItemView.as_view(), name="terminal-venda-item"),
    path("venda/item/<uuid:item_uuid>/", VendaItemDetalheView.as_view(), name="terminal-venda-item-detalhe"),
    path("venda/pagamento/", VendaPagamentoView.as_view(), name="terminal-venda-pagamento"),
    path("venda/pagamento/vale-troca/", ValeTrocaPagamentoView.as_view(), name="terminal-venda-pagamento-vale-troca"),
    path(
        "venda/pagamento/<uuid:pagamento_uuid>/",
        VendaPagamentoDetalheView.as_view(),
        name="terminal-venda-pagamento-detalhe",
    ),
    path("venda/finalizar/", VendaFinalizarView.as_view(), name="terminal-venda-finalizar"),
    path("venda/<uuid:venda_uuid>/danfe-nfce/", VendaDanfeNFCeView.as_view(), name="terminal-venda-danfe-nfce"),
    path("venda/cancelar/", VendaCancelarView.as_view(), name="terminal-venda-cancelar"),
    path("devolucoes/vendas/", DevolucaoVendasView.as_view(), name="terminal-devolucao-vendas"),
    path("devolucoes/vendas/<int:venda_id>/", DevolucaoVendaCentralView.as_view(), name="terminal-devolucao-venda-central"),
    path("devolucoes/clientes/", DevolucaoClientesView.as_view(), name="terminal-devolucao-clientes"),
    path("devolucoes/clientes/<int:cliente_id>/vendas/", DevolucaoClienteVendasView.as_view(), name="terminal-devolucao-cliente-vendas"),
    path("devolucoes/venda/<uuid:venda_uuid>/", DevolucaoConsultarView.as_view(), name="terminal-devolucao-consultar"),
    path("devolucoes/finalizar/", DevolucaoFinalizarView.as_view(), name="terminal-devolucao-finalizar"),
]
