from django.urls import path

from core.api import (
    CaixaAbrirView,
    CaixaFecharView,
    CaixaStatusView,
    FormasPagamentoView,
    OperadorContextoView,
    OperadorLoginView,
    OperadorLogoutView,
    ParearTerminalView,
    TerminalCatalogoView,
    TerminalClientesView,
    TerminalContextoView,
    TerminalHeartbeatView,
    TerminalVendedoresView,
    VendaAtualView,
    VendaCancelarView,
    VendaClienteView,
    VendaFinalizarView,
    VendaIniciarView,
    VendaItemDetalheView,
    VendaItemView,
    VendaPagamentoDetalheView,
    VendaPagamentoView,
    VendaVendedorView,
)


urlpatterns = [
    path("parear/", ParearTerminalView.as_view(), name="terminal-parear"),
    path("contexto/", TerminalContextoView.as_view(), name="terminal-contexto"),
    path("heartbeat/", TerminalHeartbeatView.as_view(), name="terminal-heartbeat"),
    path("catalogo/", TerminalCatalogoView.as_view(), name="terminal-catalogo"),
    path("clientes/", TerminalClientesView.as_view(), name="terminal-clientes"),
    path("vendedores/", TerminalVendedoresView.as_view(), name="terminal-vendedores"),
    path("operador/login/", OperadorLoginView.as_view(), name="operador-login"),
    path("operador/contexto/", OperadorContextoView.as_view(), name="operador-contexto"),
    path("operador/logout/", OperadorLogoutView.as_view(), name="operador-logout"),
    path("caixa/status/", CaixaStatusView.as_view(), name="terminal-caixa-status"),
    path("caixa/abrir/", CaixaAbrirView.as_view(), name="terminal-caixa-abrir"),
    path("caixa/fechar/", CaixaFecharView.as_view(), name="terminal-caixa-fechar"),
    path("formas-pagamento/", FormasPagamentoView.as_view(), name="terminal-formas-pagamento"),
    path("venda/atual/", VendaAtualView.as_view(), name="terminal-venda-atual"),
    path("venda/iniciar/", VendaIniciarView.as_view(), name="terminal-venda-iniciar"),
    path("venda/cliente/", VendaClienteView.as_view(), name="terminal-venda-cliente"),
    path("venda/vendedor/", VendaVendedorView.as_view(), name="terminal-venda-vendedor"),
    path("venda/item/", VendaItemView.as_view(), name="terminal-venda-item"),
    path("venda/item/<uuid:item_uuid>/", VendaItemDetalheView.as_view(), name="terminal-venda-item-detalhe"),
    path("venda/pagamento/", VendaPagamentoView.as_view(), name="terminal-venda-pagamento"),
    path(
        "venda/pagamento/<uuid:pagamento_uuid>/",
        VendaPagamentoDetalheView.as_view(),
        name="terminal-venda-pagamento-detalhe",
    ),
    path("venda/finalizar/", VendaFinalizarView.as_view(), name="terminal-venda-finalizar"),
    path("venda/cancelar/", VendaCancelarView.as_view(), name="terminal-venda-cancelar"),
]
